version: '3.4'
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 178.25.0.0/24

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      mynetwork:
        ipv4_address: 178.25.0.2

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      mynetwork:
        ipv4_address: 178.25.0.4
    ports:
      - 8081:8081
    depends_on:
      - mongo

  seq3-server:
    image: 'datalust/seq:latest'
    ports:
      - '5341:80'
      - '5342:80'
      - '5343:80'
    restart: unless-stopped
    networks:
      mynetwork:
        ipv4_address: 178.25.0.5
    environment:
      - ACCEPT_EULA=Y

  remosys.api:
    image: ${DOCKER_REGISTRY-}remosysapi
    build:
      context: .
      dockerfile: Remosys.Api/Dockerfile
    ports:
      - 5000:80
    networks:
      mynetwork:
        ipv4_address: 178.25.0.3
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo
      - seq3-server


